import { ThemeProvider } from "@/components/theme-provider";

import type { Metadata } from "next";
import { Montserrat as FontSans } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";

import { cn } from "@/lib/utils";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className="w-full flex flex-col justify-center items-center">
            <Header />
          {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
